### ISSUE TITLE
bug: 'false' in dmg 'tids' causes TypeError

### ISSUE THREAD

**Issue by caver456** [ncssar/sartopo_bg#15]
This happens during restart, on the initial loop of newFeatureCallback calls (before sync).

The log file shows the issue - how did 'false' get there (in AD104 tids) in the first place?

```
...
05:46:49 [sartopo_bg:1019:INFO] initDmd called
05:46:49 [sartopo_bg:1022:INFO] reading correlation file dmg_RDE_QDP.json
05:46:49 [sartopo_bg:1024:INFO] {
   "outings": {
...
      "AD 104": {
         "bid": "29eb932d-2664-40b2-8a63-d0eda9662faa",
         "fid": "17eb0b7d-62ea-406f-95d8-4fdedbaa5b60",
         "sid": "eac7d4f1-a40e-4170-9f10-c0d4342e070c",
         "cids": [],
         "tids": [
            [
               "a499a894-a6af-41d2-8f33-8ca8ec0023f2"
            ],
            false
         ],
         "utids": [],
         "log": [
            [
               1645797609056,
               "Added assignment boundary"
            ],
            [
               1645800989195,
               "Reimported track due to property change: AD104b"
            ],
            [
               1645801031720,
               "Added track AD104a"
            ],
            [
               1645832187165,
               "Reimported track due to property change: AD104d"
            ]
         ]
      },
...
05:46:50 [sartopo_bg:1543:INFO] newFeatureCallback: class=Shape  title=AC103c  id=1eca7ee3-8668-45c7-815d-cfb290b5755f  syncing=False
05:46:50 [sartopo_bg:1548:INFO]  source feature exists in correspondence dictionary
05:46:50 [sartopo_bg:1557:INFO]   all corresponding features exist in the debrief map
05:46:50 [sartopo_python:619:INFO] refresh requested for map QDP: 87ms since last completed sync; shorter than syncInterval; forceImmediate not specified: not syncing now
05:46:50 [sartopo_bg:1569:INFO] allTidLists:[[['1f08dafb-b9c3-410b-8bb1-7abae37dfaff', '66d649e6-b73d-4072-a585-25f3df76e378', 'bebbc192-d6b6-4c43-bd65-4b939579ae17', '80b3d969-6876-4c0c-a793-c0d0aa6252e7'], ['90ee23e0-3278-4e45-bf9e-4a7373aad6ac']], [['a499a894-a6af-41d2-8f33-8ca8ec0023f2'], False], [['245568b6-9aae-4951-84d8-9553d57e7a8d', 'c53d71c1-6ecf-44ce-a9ef-8af4651f8509']], [], [['4650795f-6eb0-4fa5-9f3b-77ffe940d195', 'b1c8461c-25dd-4266-8fe0-c4de2a598871']], [['f288e17e-71c5-420a-80c8-e767e037abab']], [['324b3c3d-6ed9-4b39-b872-96b097ba80b9']], [['2ad23385-79b6-490c-b4ae-04cabc88f128']], [['8d63e5e7-36b0-47a8-9d07-862eb1dd7bbc']]]
05:46:50 [plans_console:280:CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\plans_console\plans_console.py", line 792, in debriefButtonClicked
    self.dmg=DebriefMapGenerator(self,self.sts,self.debriefURL)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 467, in __init__
    self.newFeatureCallback(f)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 1572, in newFeatureCallback
    allTids=[a for b in [a for b in allTidLists for a in b] for a in b]
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 1572, in <listcomp>
    allTids=[a for b in [a for b in allTidLists for a in b] for a in b]
TypeError: 'bool' object is not iterable
```

The code in question:

```
    def newFeatureCallback(self,f,outingLogMessageOverride=None):
        # this function could be called from multiple places:
        # - startup (__init__ just after initDmd)
        # - doSync
        # - propertyUpdateCallback
        # - geometryUpdateCallback
        # this function is probably called from a sync thread:
        #  can't create a timer or do some GUI operations from here, etc.
        self.updateLinkLights(debriefLink=10)
        p=f['properties']
        c=p['class']
        t=p.get('title','').rstrip() # assignments with letter but not number could end in space
        sid=f['id']

        logging.info('newFeatureCallback: class='+c+'  title='+t+'  id='+sid+'  syncing='+str(self.sts1.syncing))

        # source id might have a corresponding target id; if all corresponding target ids still exist, skip    
        tids=sum(self.sts2.mapData['ids'].values(),[])    
        if sid in self.dmd['corr'].keys():
            logging.info(' source feature exists in correspondence dictionary')
            tparse=self.parseTrackName(t)
            if tparse:
                ot=tparse[0]+' '+tparse[1]
                if ot not in self.dmd['outings'].keys():
                    logging.info('  debrief map does not yet have an outing named "'+ot+'" - adding this line to the orphan list, hopefully to be picked up later')
                    for tid in self.dmd['corr'][sid]:
                        self.orphanTracksDict[tid]=t
            if all(i in tids for i in self.dmd['corr'][sid]):
                logging.info('  all corresponding features exist in the debrief map')
                if len(self.dmd['corr'][sid])==1:
                    tid=self.dmd['corr'][sid][0]
                    tf=self.sts2.getFeature(id=tid)
                    tfp=tf['properties']
                    g=f.get('geometry',None)
                    tfg=tf.get('geometry',None)
                    if tfp==p and tfg==g:
                        logging.info('   properties and geometry are unchanged; moving on...')
                    else:
                        # update un-owned features, but leave owned features alone since they have already been colored and cropped
                        allTidLists=[self.dmd['outings'][ot]['tids'] for ot in self.dmd['outings'].keys()]
                        logging.info('allTidLists:'+str(allTidLists))
                        # flatten a two-level nested list with possible empty members
                        #  https://stackoverflow.com/a/952952
                        allTids=[a for b in [a for b in allTidLists for a in b] for a in b]
                        if tid not in allTids: # only check the first corresponding feature; should be sufficient
                            logging.info('   properties and/or geometry have changed; updating debrief map feature')
                            self.sts2.editFeature(id=tid,properties=p,geometry=g)
```

from exported json, a499... = line AD104d.  It's been cropped and correctly colored in the correct folder.

The most recent test performed was to rename it on the incident map (was AD104b) to make sure the color changed, the crop happened, and it stayed in the correct folder.  I think that name change was made while DMG was running, before the restart testing; but it could have been made before restart, as part of restart testing.

**Comment by caver456** [comment]
Trying to reproduce the 'false' entry.  Here's a minimal map - added an assignment AA 101, added a line AA101a which imported as tids and cropped and colored correctly; then changed its name to AA101b on incident map.  It changed name and color and got re-cropped on the incident map - the resulting map and dmd file looks fine:

```
{
   "outings": {
      "AA 101": {
         "bid": "6d1723f8-d8a7-4b1f-ad80-1bbb50c0c6e2",
         "fid": "2a4139eb-ceb4-409d-b60c-5ad52d302a6d",
         "sid": "bc29c8f1-141d-43f0-b5eb-4532daac9219",
         "cids": [],
         "tids": [
            [
               "c6d5a310-ba17-4cd1-92ce-91a957859ec7"
            ]
         ],
         "utids": [],
         "log": [
            [
               1645885328294,
               "Added assignment boundary"
            ],
            [
               1645885361673,
               "Added track AA101a"
            ],
            [
               1645885394073,
               "Reimported track due to property change: AA101b"
            ]
         ]
      }
   },
   "corr": {
      "d45ccf15-4f78-4706-818b-77d798ad9776": [
         "c502f94a-12a9-4881-a7e1-fee1092f9809"
      ],
      "de37e873-1101-42cd-a439-1787362a30a6": [
         "c6d5a310-ba17-4cd1-92ce-91a957859ec7"
      ]
   }
}
```

Try it spanning a restart, and if that also looks fine, then maybe the false got inserted by old bad code and isn't actually an issue any more.  To see if that's the case we'd pretty much just need to call it a fluke and restart testing from the top.  It would feel better to find the smoking gun, but, that smoking gun may already be gone.

**Comment by caver456** [comment]
If the track name is changed (AA101a --> AA101c) before restart, nothing changes in the debrief map on restart - the initial newFeatureCallback silently passes it over.  So dmd also did not change.  Adding this as a separate checklist item, since it should be reimported correctly on restart.

```
...
06:30:20 [sartopo_bg:1543:INFO] newFeatureCallback: class=Shape  title=AA101c  id=de37e873-1101-42cd-a439-1787362a30a6  syncing=False
06:30:20 [sartopo_bg:1548:INFO]  source feature exists in correspondence dictionary
06:30:20 [sartopo_bg:1557:INFO]   all corresponding features exist in the debrief map
06:30:20 [sartopo_python:619:INFO] refresh requested for map BRQ: 22ms since last completed sync; shorter than syncInterval; forceImmediate not specified: not syncing now
06:30:20 [sartopo_bg:1569:INFO] allTidLists:[[['c6d5a310-ba17-4cd1-92ce-91a957859ec7']]]
06:30:20 [sartopo_bg:1543:INFO] newFeatureCallback: class=Marker  title=IC  id=d45ccf15-4f78-4706-818b-77d798ad9776  syncing=False
...
```

Before dismissing this issue as a fluke of old code, notice that the allTidLists segment of code doesn't even get triggered if there is more than one debrief feature corresponding to the incident feature - that should be fixed as well.  It makes sense for markers and non-track lines, but not for cropped tracks which may comprise several different debrief features.

**Comment by caver456** [comment]
'false' still shows up, after considerable rework of newFeatureCallback.  Narrowing it down more.  This showed up during the new-features-spanning-restart test.  Initial dmd read does not contain 'false' but after initial pre-sync it does.  The outing in question is AB 102 - it's an old outing - the assignment on the incident map has been named AB for the past several tests:

```
06:29:02 [sartopo_bg:1024:INFO] {
   "outings": {
      "AB 102": {
         "bid": "364051e0-1799-41bc-a0bb-1d2ecf647dc4",
         "fid": "66b445af-2b20-4fb1-9f38-97ee0627f5d0",
         "sid": "8fffa339-02b5-4895-8b2e-2efd3d352338",
         "cids": [],
         "tids": [
            [
               "f18e02c9-2ee4-457e-8bbe-34e7dc90920d",
               "1f9e93c4-dd69-455b-bd58-eb0d554a722c",
               "f435f16c-0f23-45a8-bbf8-5e5d27641208"
            ]
         ],
         "utids": [
            "6bdfa6c4-b9ed-4d87-a991-8b6ce3f7a3c9"
         ],
         "log": [
            [
               1646108203835,
               "Added assignment boundary"
            ],
            [
               1646108476647,
               "Geometry edited for assignment boundary"
            ],
            [
               1646108979183,
               "Added track AB102d"
            ],
            [
               1646110385956,
               "Added track AB102a"
            ],
            [
               1646143490194,
               "Reimported track due to property change: AB102e"
            ]
         ]
      },
```

dmd file after pre-sync:

```
{
   "outings": {
      "AB 102": {
         "bid": "364051e0-1799-41bc-a0bb-1d2ecf647dc4",
         "fid": "66b445af-2b20-4fb1-9f38-97ee0627f5d0",
         "sid": "8fffa339-02b5-4895-8b2e-2efd3d352338",
         "cids": [],
         "tids": [
            [
               "f18e02c9-2ee4-457e-8bbe-34e7dc90920d",
               "1f9e93c4-dd69-455b-bd58-eb0d554a722c",
               "f435f16c-0f23-45a8-bbf8-5e5d27641208"
            ],
            false
         ],
         "utids": [],
         "log": [
            [
               1646108203835,
               "Added assignment boundary"
            ],
            [
               1646108476647,
               "Geometry edited for assignment boundary"
            ],
            [
               1646108979183,
               "Added track AB102d"
            ],
            [
               1646110385956,
               "Added track AB102a"
            ],
            [
               1646143490194,
               "Reimported track due to property change: AB102e"
            ]
         ]
      },

```
Snippet from the same log file, during pre-sync, farther down in the log after initDmd (above) - interesting that this happens during processing of new assignment AT 131:

```
06:29:03 [sartopo_bg:1568:INFO] newFeatureCallback: class=Assignment  title=AT 131  id=123efd36-a330-4b82-a07a-346900465167  syncing=False
06:29:03 [sartopo_bg:1214:INFO]  checking to see if this outing (title="AT 131" id=123efd36-a330-4b82-a07a-346900465167) already exists...
06:29:03 [sartopo_bg:1262:INFO]   no, the outing does not already exist; adding it now
06:29:03 [sartopo_python:729:INFO] sending post to http://localhost:8080/api/v1/map/FHH/Folder
06:29:03 [sartopo_python:753:INFO] {'properties': {'title': 'AT 131'}}
06:29:03 [sartopo_bg:1329:INFO] Previously imported track "AT131b" appears to belong to newly imported outing "AT 131".  Importing the uncropped track to the outing.
06:29:03 [sartopo_python:1345:INFO] editFeature called
06:29:03 [sartopo_python:1386:INFO]  id specified: 112bf337-7403-4344-9ffa-6cdc938bcceb
06:29:03 [sartopo_python:729:INFO] sending post to http://localhost:8080/api/v1/map/FHH/Shape/112bf337-7403-4344-9ffa-6cdc938bcceb
06:29:03 [sartopo_python:753:INFO] {'type': 'Feature', 'id': '112bf337-7403-4344-9ffa-6cdc938bcceb', 'properties': {'creator': '3MA660', 'stroke-opacity': 1, 'pattern': 'solid', 'description': '', 'stroke-width': 2, 'title': 'AT131b', 'fill': '#00CD00', 'class': 'Shape', 'updated': 0, 'stroke': '#00CD00', 'fill-opacity': 0.1, 'gpstype': 'TRACK', 'folderId': '01b140a7-5e95-44ef-9203-4343b62e9368'}}
06:29:03 [sartopo_bg:1296:INFO] drawing boundary for area assignment AT 131
06:29:03 [sartopo_python:729:INFO] sending post to http://localhost:8080/api/v1/map/FHH/Shape
06:29:03 [sartopo_python:753:INFO] {'json': '{"properties": {"title": "AT 131", "folderId": "01b140a7-5e95-44ef-9203-4343b62e9368", "description": "", "stroke-width": 8, "stroke-opacity": 0.4, "stroke": "#FF0000", "fill": "#FF0000", "fill-opacity": 0.0, "gpstype": "TRACK"}, "geometry": {"type": "Polygon", "coordinates": "1 segment (4 points)"}}'}
06:29:04 [sartopo_bg:1307:INFO] boundary created for assignment AT 131: 4b6e3098-3290-4d10-bb20-af3d99329b6d
06:29:04 [sartopo_python:621:INFO] refresh requested for map FHH: 1413ms since last completed sync; shorter than syncInterval; forceImmediate not specified: not syncing now
06:29:04 [sartopo_bg:1486:INFO]   Outing AB 102: cropping 1 uncropped track(s):['6bdfa6c4-b9ed-4d87-a991-8b6ce3f7a3c9']
06:29:04 [sartopo_python:621:INFO] refresh requested for map FHH: 1413ms since last completed sync; shorter than syncInterval; forceImmediate not specified: not syncing now
06:29:04 [sartopo_python:1269:INFO] getFeatures: No features match the specified criteria.
06:29:04 [sartopo_python:1270:INFO]   (was looking for featureClass=None  title=None  id=6bdfa6c4-b9ed-4d87-a991-8b6ce3f7a3c9)
06:29:04 [sartopo_python:1905:WARNING] Target shape 6bdfa6c4-b9ed-4d87-a991-8b6ce3f7a3c9 not found; operation aborted.
06:29:04 [sartopo_bg:1508:ERROR]     corresponding source map line id could not be determined
06:29:04 [sartopo_bg:1509:ERROR]     corresponding source line id list:[]
06:29:04 [sartopo_bg:1486:INFO]   Outing AT 131: cropping 1 uncropped track(s):['112bf337-7403-4344-9ffa-6cdc938bcceb']

```

In a previous test, track AB102a was renamed to AB102e before restart.  It was re-imported and cropped and colored correctly as you can see in the log entries, but the old track was left in utids (as a single uncropped debrief map feature).  That feature no longer exists in the debrief map, so the 'getFeatures: No features match' line is probably the direct cause, and the fact that the old track was left in utids is probably the root cause.  Try to make a minimal test case.

**Comment by caver456** [comment]
Did not directly reproduce the 'false' entry, but, adding a call to deletedFeatureCallback whenever newFeatureCallback determines that a feature needs to be re-imported does get rid of the old feature from tids and utids which apparently does the trick.  Will leave this open until a full test is complete.

**Comment by caver456** [comment]
This looks more like the smoking gun - actually part of a different test item (no restart needed) - drawing a track with a correctly formatted title for a different outing:

1. assignment AA 101
2. assignment AB 102
3. draw line 'AA101a' over AB 102 - it's really a track for AB - it was drawn in the right place, with the wrong title
 --> AA101a is imported as a uncropped track to AA 101
4. change title AA101a to AB102a
 --> the initial utid is deleted from the debrief map, but, the AA 101 utids entry remains, which is now an orphan
5. add assignment AC 103
 --> addOuting calls cropUncroppedTracks which shows the error messages

After 4, the utids entry still exists in the dmd file; after 5, that tid has been replaced with 'false' in the dmd file.

So - two actions to take, in this order:
- in step 5, prevent 'false' from showing up in utids - if the utid is an orphan, just move on
- in step 4, prevent the orphan utid after title change

**Comment by caver456** [comment]
this was the code that created the 'false' entry:

croppedTrackLines=self.sts2.crop(utid,bid,beyond=cropDegrees)
self.dmd['outings'][outingName]['tids'].append(croppedTrackLines)

wrapped the second line in a conditional:
croppedTrackLines=self.sts2.crop(utid,bid,beyond=cropDegrees)
if croppedTrackLines:
    self.dmd['outings'][outingName]['tids'].append(croppedTrackLines)

That prevents the 'false' entry.  Also, since orphans are cleaned up at the end of cropUncroppedTracks anyway, by setting utids to [], that's probably good enough, combined with changing the messages from errors to warnings - since there don't seem to be any other ill effects from orphan utids entries, and preventing the orphans in the first place would be more invasive.

This resolves the simple case where the outings are all current (source assignment titles currently match outing titles) and we're not spanning restart.  Need to test for the other three cases:
- current outings, spanning restart
- old outing(s), within session
- old outing(s), spanning restart

**Comment by caver456** [comment]
All the other cases seem to be fine.  It looks like everything is resolved, with the possible exception of finding an earlier place to prevent orphan utids / to remove them when the track is shifted to a different outing due to name change (during propertyUpdateCallback), but, that doesn't seem to affect anything else.

Leaving this issue open until a full re-test is done.

**Comment by caver456** [comment]
Fixed in recent commit to plans_console; all of the current tests are working.
