### ISSUE TITLE
handle clues that are not owned by any assignment

### ISSUE THREAD

**Issue by caver456** [ncssar/sartopo_bg#20]
If the owning assignment was never set in sartopo, the json will not have any 'assignmentId' key.  The code currently does not handle this case:

![image](https://user-images.githubusercontent.com/18752102/177785325-228797e9-a090-45a2-9ad1-2f1adde8209d.png)

leads to

```
06:05:07 [sartopo_bg:2228:INFO] newFeatureCallback: class=Clue  title=Clue 01  id=dcb3c9b7-1d29-4662-a6a9-fe9234031466  syncing=True
06:05:07 [sartopo_bg:2299:INFO]  no correspondence entry found; adding the feature to the debrief map
06:05:07 [sartopo_bg:2112:INFO] creating clue 'Clue 01' in default folder
06:05:07 [sartopo_python:791:INFO] sending post to http://localhost:8080/api/v1/map/9MT/Marker
06:05:07 [sartopo_python:817:INFO] {'properties': {'class': 'Marker', 'updated': 0, 'marker-color': '#FF0000', 'marker-symbol': 'clue', 'marker-size': 1, 'marker-rotation': None, 'title': 'Clue 01', 'description': 'civilian reported possible sighting of MP walking on Scotts Flat Road'}, 'geometry': {'type': 'Point', 'coordinates': [-120.92284921131193, 39.283902984196686]}, 'type': 'Feature'}
06:05:07 [plans_console:288:CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\plans_console\plans_console.py", line 870, in debriefButtonClicked
    self.dmg=DebriefMapGenerator(self,self.sts,self.debriefURL)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 577, in __init__
    self.newFeatureCallback(f)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 2309, in newFeatureCallback
    self.addClue(f)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 2114, in addClue
    aid=p['assignmentId']
KeyError: 'assignmentId'
```

**Comment by caver456** [comment]
fixed by commit in plans_console

**Comment by caver456** [comment]
Reopening - got a similar error during restart/restore.  This one was inside propertyUpdateCallback.  Adding a couple of items to the testing checklist to cover these cases, both at initial debrief map creation, and during property update.

Basically we want to make sure that changing a clue's assignment is handled propertly, from unassigned to assigned; from assigned to other assigned; and (just to be thorough) from assigned to unassigned.

```
06:38:41 [sartopo_bg:2233:INFO] newFeatureCallback: class=Clue  title=Clue 01  id=dcb3c9b7-1d29-4662-a6a9-fe9234031466  syncing=True
06:38:41 [sartopo_bg:2263:INFO]  source feature exists in correspondence dictionary
06:38:41 [sartopo_python:658:INFO] refresh requested for map 1TV: sync already in progress
06:38:41 [sartopo_bg:2288:INFO]   but the properties are not the same as the incident map feature; modifying properties...
06:38:41 [sartopo_python:658:INFO] refresh requested for map 92V: sync already in progress
06:38:41 [sartopo_bg:2486:INFO] propertyUpdateCallback called for Clue:Clue 01
06:38:41 [sartopo_bg:2536:INFO]  exactly one debrief map feature corresponds to the source map feature; updating the debrief map feature properties
06:38:41 [sartopo_python:658:INFO] refresh requested for map 1TV: sync already in progress
06:38:41 [plans_console:288:CRITICAL] Uncaught exception
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\plans_console\plans_console.py", line 1373, in <module>
    main()
  File "C:\Users\caver\Documents\GitHub\plans_console\plans_console.py", line 1368, in main
    w = PlansConsole(app)
  File "C:\Users\caver\Documents\GitHub\plans_console\plans_console.py", line 542, in __init__
    self.debriefButtonClicked()
  File "C:\Users\caver\Documents\GitHub\plans_console\plans_console.py", line 870, in debriefButtonClicked
    self.dmg=DebriefMapGenerator(self,self.sts,self.debriefURL)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 578, in __init__
    self.newFeatureCallback(f)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 2289, in newFeatureCallback
    self.propertyUpdateCallback(f)
  File "C:\Users\caver\Documents\GitHub\plans_console\sartopo_bg.py", line 2564, in propertyUpdateCallback
    aid=sp['assignmentId']
KeyError: 'assignmentId'
```

**Comment by caver456** [comment]
fixed again in plans_console
